# Generated by Django 4.2.27 on 2026-03-10 01:09

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Authority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authority_name', models.CharField(max_length=20, verbose_name='権限名')),
                ('authority_code', models.CharField(max_length=20, verbose_name='権限')),
            ],
            options={
                'verbose_name': 'Authority',
                'verbose_name_plural': 'Authoritys',
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_name', models.CharField(max_length=20, verbose_name='名前')),
                ('color', models.CharField(max_length=20, verbose_name='色')),
            ],
            options={
                'verbose_name': '色管理',
                'verbose_name_plural': '色管理',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=20, verbose_name='タイトル')),
                ('start_date', models.DateField(verbose_name='開始日')),
                ('start_time', models.TimeField(blank=True, default=datetime.time(0, 0), verbose_name='開始時間')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='終了日')),
                ('end_time', models.TimeField(blank=True, default=datetime.time(23, 0), null=True, verbose_name='終了時間')),
                ('allday', models.BooleanField(default=True, verbose_name='終日設定')),
                ('url', models.URLField(blank=True, null=True, verbose_name='URL')),
                ('location', models.CharField(blank=True, max_length=20, null=True, verbose_name='場所')),
                ('memo', models.TextField(blank=True, max_length=500, null=True, verbose_name='メモ')),
            ],
            options={
                'verbose_name': '予定',
                'verbose_name_plural': '予定',
            },
        ),
        migrations.CreateModel(
            name='Repeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repeat_name', models.CharField(max_length=10, verbose_name='名前')),
                ('repeat_code', models.CharField(blank=True, max_length=30, null=True, verbose_name='コード')),
            ],
            options={
                'verbose_name': '繰り返し管理',
                'verbose_name_plural': '繰り返し管理',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('room_name', models.CharField(max_length=20, verbose_name='ルーム名')),
                ('room_description', models.TextField(blank=True, max_length=500, null=True, verbose_name='説明')),
                ('is_personal', models.BooleanField(default=False, verbose_name='個人用ルームか')),
                ('join_url', models.CharField(editable=False, max_length=20, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'カレンダー',
                'verbose_name_plural': 'カレンダー',
            },
        ),
        migrations.CreateModel(
            name='RoomMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('authority', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='DayLine_1_DayLine.authority', verbose_name='権限')),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='DayLine_1_DayLine.room', verbose_name='ルーム名')),
            ],
            options={
                'verbose_name': 'カレンダーメンバー',
                'verbose_name_plural': 'カレンダーメンバー',
            },
        ),
    ]
