# Generated by Django 4.2.27 on 2026-03-21 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DayLine_1_DayLine', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='room_img',
            field=models.ImageField(blank=True, default='defaults\\calendar\\defalt_calendar_img.png', null=True, upload_to='', verbose_name='ルームアイコン'),
        ),
    ]
