# Generated by Django 6.0.3 on 2026-04-28 13:32

import DayLine_1_DayLine.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DayLine_1_DayLine', '0004_event_created_at_event_updated_at_roommember_join_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roommember',
            name='authority',
            field=models.ForeignKey(default=DayLine_1_DayLine.models.get_default_authority, on_delete=django.db.models.deletion.PROTECT, to='DayLine_1_DayLine.authority', verbose_name='権限'),
        ),
        migrations.CreateModel(
            name='ToDoEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50, verbose_name='タイトル')),
                ('checkTodo', models.BooleanField(default=False, verbose_name='チェック')),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='DayLine_1_DayLine.event', verbose_name='イベント')),
            ],
            options={
                'verbose_name': 'ToDo',
                'verbose_name_plural': 'ToDo',
            },
        ),
    ]
