# Generated by Django 6.0.3 on 2026-04-23 01:13

import DayLine_1_DayLine.models
import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DayLine_1_DayLine', '0004_event_created_at_event_updated_at_roommember_join_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_img',
            field=cloudinary.models.CloudinaryField(blank=True, default='images/defaults/calendar/defalt_calendar_img.png', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='roommember',
            name='authority',
            field=models.ForeignKey(default=DayLine_1_DayLine.models.get_default_authority, on_delete=django.db.models.deletion.PROTECT, to='DayLine_1_DayLine.authority', verbose_name='権限'),
        ),
    ]
