# Generated by Django 6.0.3 on 2026-04-23 14:11

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DayLine_1_DayLine', '0005_alter_room_room_img_alter_roommember_authority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_img',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
    ]
