# Generated by Django 5.2.2 on 2026-06-12 06:20

import DayLine_1_DayLine.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DayLine_1_DayLine', '0005_alter_roommember_authority_todoevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_img',
            field=models.ImageField(blank=True, default='images/defaults/calendar/defalt_calendar_img.png', null=True, upload_to=DayLine_1_DayLine.models.user_icon_upload_path, verbose_name='ルームアイコン'),
        ),
    ]
