# Generated by Django 6.0.3 on 2026-04-24 02:44

import DayLine_1_DayLine.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DayLine_1_DayLine', '0006_alter_room_room_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roommember',
            name='authority',
            field=models.ForeignKey(default=DayLine_1_DayLine.models.get_default_authority, on_delete=django.db.models.deletion.PROTECT, to='DayLine_1_DayLine.authority', verbose_name='権限'),
        ),
    ]
