# Generated by Django 4.2.27 on 2026-03-16 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TermsOfUse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_number', models.IntegerField(max_length=100, verbose_name='条')),
                ('article_name', models.CharField(max_length=1000, verbose_name='条文タイトル')),
                ('article_description', models.TextField(max_length=2000, verbose_name='条文')),
            ],
            options={
                'verbose_name': '利用規約',
                'verbose_name_plural': '利用規約',
            },
        ),
    ]
