"""
Django settings for DayLine project.

Generated by 'django-admin startproject' using Django 4.2.27.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
from dotenv import load_dotenv
load_dotenv()
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-fmkooc)(4@u#1)zl!93=ho&je34o2!$gpor!o1do3(qvgjj=d='

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # 自動リロード
    'django_browser_reload',
    # modelsでカラーコードを使える
    'colorfield',

    'DayLine_1_DayLine',
    'DayLine_2_top',
    'DayLine_3_accounts',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # 自動リロード
    "django_browser_reload.middleware.BrowserReloadMiddleware",
    #Renderに必用
    'whitenoise.storage.CompressedManifestStaticFilesStorage',

]

ROOT_URLCONF = 'DayLine.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'DayLine.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

import os
STATIC_URL = 'static/'
STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'static'),
)
STATIC_ROOT = BASE_DIR / 'staticfiles'
#Renderで必用
STORAGES = {
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}
IMAGE_ROOT = os.path.join(BASE_DIR, 'images')
IMAGE_URL = 'images/'


LANGUAGE_CODE = 'ja'

TIME_ZONE = 'Asia/Tokyo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
APPEND_SLASH = True

# ユーザーモデルを登録
AUTH_USER_MODEL = 'DayLine_3_accounts.CustomUser'
# メールアドレスで認証
USERNAME_FIELD = 'email'

LOGIN_REDIRECT_URL = 'DayLine_1_DayLine:index'

LOGOUT_REDIRECT_URL = 'DayLine_2_top:top'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# メール送信の設定
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = "maruriku0655@gmail.com"
EMAIL_HOST_PASSWORD = "fiyr tcpw ugff lasd"
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER


#生成ai用のapiキー
# settings.py
import os
GROQ_API_KEY = os.environ.get('GROQ_API_KEY', '')

"""
# 仮サーバーを立てるために必要な奴
#サーバー実行手順 
# 1. 1つ目のcmdでpython manage.py runserver 8000を実行
# 2. 2つ目のcmdでngrok http 8000を実行
# サーバー実行完了
ALLOWED_HOSTS = [
    'nongarrulous-antone-overrighteous.ngrok-free.dev',
    'localhost',
    '127.0.0.1',
]
CSRF_TRUSTED_ORIGINS = [
    'https://nongarrulous-antone-overrighteous.ngrok-free.dev',
]
"""



DATABASE_URL = "postgresql://dayline_db_user:79vJlx4em64Wa10vr2OuFOctALCopXGY@dpg-d7k98q5ckfvc73bhhpmg-a/dayline_db"
