# Generated by Django 4.2.27 on 2026-03-20 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DayLine_3_accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
