# Generated by Django 4.2.27 on 2026-03-21 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DayLine_3_accounts', '0002_customuser_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='icon',
            field=models.ImageField(blank=True, default='defaults/user_icon/defalt-icon-9.svg', null=True, upload_to='images'),
        ),
    ]
