# Generated by Django 6.0.3 on 2026-03-30 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DayLine_3_accounts', '0003_alter_customuser_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='icon',
            field=models.ImageField(blank=True, default='images/defaults/user_icon/defalt-icon-6.svg', null=True, upload_to='images/user_icons'),
        ),
    ]
