# Generated by Django 6.0.3 on 2026-04-23 01:13

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DayLine_3_accounts', '0004_alter_customuser_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='icon',
            field=cloudinary.models.CloudinaryField(blank=True, default='images/defaults/user_icon/defalt-icon-1.svg', max_length=255, null=True, verbose_name='image'),
        ),
    ]
