# Generated by Django 6.0.3 on 2026-05-05 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DayLine_3_accounts', '0005_alter_customuser_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='icon',
            field=models.ImageField(blank=True, default='images/defaults/user_icon/defalt-icon-8.svg', null=True, upload_to='images/user_icons'),
        ),
    ]
