# Generated by Django 6.0.3 on 2026-04-23 14:11

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DayLine_3_accounts', '0005_alter_customuser_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='icon',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
    ]
