# Generated by Django 5.2.2 on 2026-06-12 06:20

import DayLine_3_accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DayLine_3_accounts', '0007_alter_customuser_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='icon',
            field=models.ImageField(blank=True, default=DayLine_3_accounts.models.get_default_icon, null=True, upload_to=DayLine_3_accounts.models.user_icon_upload_path),
        ),
    ]
